name: K6 Load Test
on: [push]
jobs:
  build:
    name: K6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v5

      - name: Step 2 - Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Step 3 - Run K6 Load Test
        uses: grafana/run-k6-action@v1
        with:
          path: ./scripts/tc1.js

      - run: ls & mkdir report & mv index.html report

      - name: Step 4 - Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Performance Test Report
          path: ./report
