name: K6 Load Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v5

      - name: Step 2 - Run K6 Load Test
        uses: grafana/run-k6-action@v1
        with:
          filename: scripts/tc1.js